with-expecter: True
mockname: "Mock{{.InterfaceName}}"
filename: "{{.MockName}}.go"
inpackage: True
dir: ./server
packages:
  github.com/mkaminski/goaim/server:
    interfaces:
      FeedbagManager:
      SessionManager:
      ProfileManager:
      ICBMHandler:
      LocateHandler:
      OServiceHandler: