with-expecter: true
dir: "{{.InterfaceDir}}"
mockname: "mock{{.InterfaceName}}"
inpackage: true
packages:
  github.com/mk6i/retro-aim-server/server/oscar:
    interfaces:
      AuthService:
        config:
          filename: "mock_auth_test.go"
      Handler:
        config:
          filename: "mock_handler_test.go"
      OnlineNotifier:
        config:
          filename: "mock_online_notifier_test.go"
      UserManager:
        config:
          filename: "mock_user_manager_test.go"
      RateLimitUpdater:
        config:
          filename: "mock_rate_limit_updater_test.go"
      BuddyListRegistry:
        config:
          filename: "mock_buddy_list_registry_test.go"
      DepartureNotifier:
        config:
          filename: "mock_departure_notifier_test.go"
      ChatSessionManager:
        config:
          filename: "mock_chat_session_manager_test.go"
      AdminService:
        config:
          filename: "mock_admin_service_test.go"
      BARTService:
        config:
          filename: "mock_bart_service_test.go"
      BuddyService:
        config:
          filename: "mock_buddy_service_test.go"
      ChatNavService:
        config:
          filename: "mock_chat_nav_service_test.go"
      ChatService:
        config:
          filename: "mock_chat_service_test.go"
      FeedbagService:
        config:
          filename: "mock_feedbag_service_test.go"
      ICBMService:
        config:
          filename: "mock_icbm_service_test.go"
      ICQService:
        config:
          filename: "mock_icq_service_test.go"
      LocateService:
        config:
          filename: "mock_locate_service_test.go"
      ODirService:
        config:
          filename: "mock_odir_service_test.go"
      OServiceService:
        config:
          filename: "mock_oservice_service_test.go"
      PermitDenyService:
        config:
          filename: "mock_permit_deny_service_test.go"
      ResponseWriter:
        config:
          filename: "mock_response_writer_test.go"
      StatsService:
        config:
          filename: "mock_stats_service_test.go"
      UserLookupService:
        config:
          filename: "mock_user_lookup_service_test.go"
  github.com/mk6i/retro-aim-server/server/http:
    interfaces:
      AccountManager:
        config:
          filename: "mock_account_manager_test.go"
      AccountRetriever:
        config:
          filename: "mock_account_retriever_test.go"
      BuddyIconRetriever:
        config:
          filename: "mock_buddy_icon_retriever_test.go"
      ChatRoomCreator:
        config:
          filename: "mock_chat_room_creator_test.go"
      ChatRoomRetriever:
        config:
          filename: "mock_chat_room_retriever_test.go"
      ChatSessionRetriever:
        config:
          filename: "mock_chat_session_retriever_test.go"
      DirectoryManager:
        config:
          filename: "mock_directory_manager_test.go"
      FeedBagRetriever:
        config:
          filename: "mock_feedbag_retriever_test.go"
      MessageRelayer:
        config:
          filename: "mock_message_relayer_test.go"
      ProfileRetriever:
        config:
          filename: "mock_profile_retriever_test.go"
      SessionRetriever:
        config:
          filename: "mock_session_retriever_test.go"
      UserManager:
        config:
          filename: "mock_user_manager_test.go"
  github.com/mk6i/retro-aim-server/foodgroup:
    interfaces:
      AccountManager:
        config:
          filename: "mock_account_manager_test.go"
      BuddyIconManager:
        config:
          filename: "mock_buddy_icon_manager_test.go"
      buddyBroadcaster:
        config:
          filename: "mock_buddy_broadcaster_test.go"
      RelationshipFetcher:
        config:
          filename: "mock_relationship_fetcher_test.go"
      ChatMessageRelayer:
        config:
          filename: "mock_chat_message_relayer_test.go"
      ChatRoomRegistry:
        config:
          filename: "mock_chat_room_registry_test.go"
      ChatSessionRegistry:
        config:
          filename: "mock_chat_session_registry_test.go"
      CookieBaker:
        config:
          filename: "mock_cookie_baker_test.go"
      FeedbagManager:
        config:
          filename: "mock_feedbag_manager_test.go"
      ICQUserFinder:
        config:
          filename: "mock_icq_user_finder_test.go"
      ICQUserUpdater:
        config:
          filename: "mock_icq_user_updater_test.go"
      LegacyBuddyListManager:
        config:
          filename: "mock_legacy_buddy_list_manager_test.go"
      ClientSideBuddyListManager:
        config:
          filename: "mock_client_side_buddy_list_manager_test.go"
      MessageRelayer:
        config:
          filename: "mock_message_relayer_test.go"
      OfflineMessageManager:
        config:
          filename: "mock_offline_message_manager_test.go"
      ProfileManager:
        config:
          filename: "mock_profile_manager_test.go"
      SessionRegistry:
        config:
          filename: "mock_session_registry_test.go"
      SessionRetriever:
        config:
          filename: "mock_session_retriever_test.go"
      UserManager:
        config:
          filename: "mock_user_manager_manager_test.go"
  github.com/mk6i/retro-aim-server/server/toc:
    interfaces:
      AdminService:
        config:
          filename: "mock_admin_service_test.go"
      BuddyService:
        config:
          filename: "mock_buddy_service_test.go"
      ChatService:
        config:
          filename: "mock_chat_service_test.go"
      ChatNavService:
        config:
          filename: "mock_chat_nav_service_test.go"
      ICBMService:
        config:
          filename: "mock_icbm_service_test.go"
      OServiceService:
        config:
          filename: "mock_oservice_service_test.go"
      AuthService:
        config:
          filename: "mock_auth_service_test.go"
      LocateService:
        config:
          filename: "mock_locate_service_test.go"
      DirSearchService:
        config:
          filename: "mock_dir_search_service_test.go"
      PermitDenyService:
        config:
          filename: "mock_permit_deny_service_test.go"
      BuddyListRegistry:
        config:
          filename: "mock_buddy_list_registry_test.go"
      TOCConfigStore:
        config:
          filename: "mock_toc_config_store_test.go"
      CookieBaker:
        config:
          filename: "mock_cookie_baker_test.go"
  github.com/mk6i/retro-aim-server/server/kerberos:
    interfaces:
      AuthService:
        config:
          filename: "mock_auth_test.go"