coverage:
  round: down
  range: 70..79
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
ignore:
  - server/webapi
  - state/webapi*
  - state/web_api*