// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package webapi

import (
	"context"

	"github.com/mk6i/open-oscar-server/state"
	"github.com/mk6i/open-oscar-server/wire"
	mock "github.com/stretchr/testify/mock"
)

// newMockOServiceService creates a new instance of mockOServiceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockOServiceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockOServiceService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockOServiceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockOServiceService is an autogenerated mock type for the OServiceService type
type mockOServiceService struct {
	mock.Mock
}

type mockOServiceService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockOServiceService) EXPECT() *mockOServiceService_Expecter {
	return &mockOServiceService_Expecter{mock: &_m.Mock}
}

// ClientOnline provides a mock function for the type mockOServiceService
func (_mock *mockOServiceService) ClientOnline(ctx context.Context, service uint16, inBody wire.SNAC_0x01_0x02_OServiceClientOnline, instance *state.SessionInstance) error {
	ret := _mock.Called(ctx, service, inBody, instance)

	if len(ret) == 0 {
		panic("no return value specified for ClientOnline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint16, wire.SNAC_0x01_0x02_OServiceClientOnline, *state.SessionInstance) error); ok {
		r0 = returnFunc(ctx, service, inBody, instance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockOServiceService_ClientOnline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientOnline'
type mockOServiceService_ClientOnline_Call struct {
	*mock.Call
}

// ClientOnline is a helper method to define mock.On call
//   - ctx context.Context
//   - service uint16
//   - inBody wire.SNAC_0x01_0x02_OServiceClientOnline
//   - instance *state.SessionInstance
func (_e *mockOServiceService_Expecter) ClientOnline(ctx any, service any, inBody any, instance any) *mockOServiceService_ClientOnline_Call {
	return &mockOServiceService_ClientOnline_Call{Call: _e.mock.On("ClientOnline", ctx, service, inBody, instance)}
}

func (_c *mockOServiceService_ClientOnline_Call) Run(run func(ctx context.Context, service uint16, inBody wire.SNAC_0x01_0x02_OServiceClientOnline, instance *state.SessionInstance)) *mockOServiceService_ClientOnline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint16
		if args[1] != nil {
			arg1 = args[1].(uint16)
		}
		var arg2 wire.SNAC_0x01_0x02_OServiceClientOnline
		if args[2] != nil {
			arg2 = args[2].(wire.SNAC_0x01_0x02_OServiceClientOnline)
		}
		var arg3 *state.SessionInstance
		if args[3] != nil {
			arg3 = args[3].(*state.SessionInstance)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockOServiceService_ClientOnline_Call) Return(err error) *mockOServiceService_ClientOnline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockOServiceService_ClientOnline_Call) RunAndReturn(run func(ctx context.Context, service uint16, inBody wire.SNAC_0x01_0x02_OServiceClientOnline, instance *state.SessionInstance) error) *mockOServiceService_ClientOnline_Call {
	_c.Call.Return(run)
	return _c
}

// MonitorRateLimits provides a mock function for the type mockOServiceService
func (_mock *mockOServiceService) MonitorRateLimits(ctx context.Context, session *state.Session) {
	_mock.Called(ctx, session)
	return
}

// mockOServiceService_MonitorRateLimits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MonitorRateLimits'
type mockOServiceService_MonitorRateLimits_Call struct {
	*mock.Call
}

// MonitorRateLimits is a helper method to define mock.On call
//   - ctx context.Context
//   - session *state.Session
func (_e *mockOServiceService_Expecter) MonitorRateLimits(ctx any, session any) *mockOServiceService_MonitorRateLimits_Call {
	return &mockOServiceService_MonitorRateLimits_Call{Call: _e.mock.On("MonitorRateLimits", ctx, session)}
}

func (_c *mockOServiceService_MonitorRateLimits_Call) Run(run func(ctx context.Context, session *state.Session)) *mockOServiceService_MonitorRateLimits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.Session
		if args[1] != nil {
			arg1 = args[1].(*state.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockOServiceService_MonitorRateLimits_Call) Return() *mockOServiceService_MonitorRateLimits_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockOServiceService_MonitorRateLimits_Call) RunAndReturn(run func(ctx context.Context, session *state.Session)) *mockOServiceService_MonitorRateLimits_Call {
	_c.Run(run)
	return _c
}

// RateParamsSubAdd provides a mock function for the type mockOServiceService
func (_mock *mockOServiceService) RateParamsSubAdd(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x01_0x08_OServiceRateParamsSubAdd) {
	_mock.Called(ctx, instance, inBody)
	return
}

// mockOServiceService_RateParamsSubAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RateParamsSubAdd'
type mockOServiceService_RateParamsSubAdd_Call struct {
	*mock.Call
}

// RateParamsSubAdd is a helper method to define mock.On call
//   - ctx context.Context
//   - instance *state.SessionInstance
//   - inBody wire.SNAC_0x01_0x08_OServiceRateParamsSubAdd
func (_e *mockOServiceService_Expecter) RateParamsSubAdd(ctx any, instance any, inBody any) *mockOServiceService_RateParamsSubAdd_Call {
	return &mockOServiceService_RateParamsSubAdd_Call{Call: _e.mock.On("RateParamsSubAdd", ctx, instance, inBody)}
}

func (_c *mockOServiceService_RateParamsSubAdd_Call) Run(run func(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x01_0x08_OServiceRateParamsSubAdd)) *mockOServiceService_RateParamsSubAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.SessionInstance
		if args[1] != nil {
			arg1 = args[1].(*state.SessionInstance)
		}
		var arg2 wire.SNAC_0x01_0x08_OServiceRateParamsSubAdd
		if args[2] != nil {
			arg2 = args[2].(wire.SNAC_0x01_0x08_OServiceRateParamsSubAdd)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockOServiceService_RateParamsSubAdd_Call) Return() *mockOServiceService_RateParamsSubAdd_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockOServiceService_RateParamsSubAdd_Call) RunAndReturn(run func(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x01_0x08_OServiceRateParamsSubAdd)) *mockOServiceService_RateParamsSubAdd_Call {
	_c.Run(run)
	return _c
}

// SetUserInfoFields provides a mock function for the type mockOServiceService
func (_mock *mockOServiceService) SetUserInfoFields(ctx context.Context, instance *state.SessionInstance, inFrame wire.SNACFrame, inBody wire.SNAC_0x01_0x1E_OServiceSetUserInfoFields) error {
	ret := _mock.Called(ctx, instance, inFrame, inBody)

	if len(ret) == 0 {
		panic("no return value specified for SetUserInfoFields")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance, wire.SNACFrame, wire.SNAC_0x01_0x1E_OServiceSetUserInfoFields) error); ok {
		r0 = returnFunc(ctx, instance, inFrame, inBody)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockOServiceService_SetUserInfoFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserInfoFields'
type mockOServiceService_SetUserInfoFields_Call struct {
	*mock.Call
}

// SetUserInfoFields is a helper method to define mock.On call
//   - ctx context.Context
//   - instance *state.SessionInstance
//   - inFrame wire.SNACFrame
//   - inBody wire.SNAC_0x01_0x1E_OServiceSetUserInfoFields
func (_e *mockOServiceService_Expecter) SetUserInfoFields(ctx any, instance any, inFrame any, inBody any) *mockOServiceService_SetUserInfoFields_Call {
	return &mockOServiceService_SetUserInfoFields_Call{Call: _e.mock.On("SetUserInfoFields", ctx, instance, inFrame, inBody)}
}

func (_c *mockOServiceService_SetUserInfoFields_Call) Run(run func(ctx context.Context, instance *state.SessionInstance, inFrame wire.SNACFrame, inBody wire.SNAC_0x01_0x1E_OServiceSetUserInfoFields)) *mockOServiceService_SetUserInfoFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.SessionInstance
		if args[1] != nil {
			arg1 = args[1].(*state.SessionInstance)
		}
		var arg2 wire.SNACFrame
		if args[2] != nil {
			arg2 = args[2].(wire.SNACFrame)
		}
		var arg3 wire.SNAC_0x01_0x1E_OServiceSetUserInfoFields
		if args[3] != nil {
			arg3 = args[3].(wire.SNAC_0x01_0x1E_OServiceSetUserInfoFields)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockOServiceService_SetUserInfoFields_Call) Return(err error) *mockOServiceService_SetUserInfoFields_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockOServiceService_SetUserInfoFields_Call) RunAndReturn(run func(ctx context.Context, instance *state.SessionInstance, inFrame wire.SNACFrame, inBody wire.SNAC_0x01_0x1E_OServiceSetUserInfoFields) error) *mockOServiceService_SetUserInfoFields_Call {
	_c.Call.Return(run)
	return _c
}
