// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oscar

import (
	"context"

	"github.com/mk6i/retro-aim-server/config"
	"github.com/mk6i/retro-aim-server/state"
	"github.com/mk6i/retro-aim-server/wire"
	mock "github.com/stretchr/testify/mock"
)

// newMockOServiceService creates a new instance of mockOServiceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockOServiceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockOServiceService {
	mock := &mockOServiceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockOServiceService is an autogenerated mock type for the OServiceService type
type mockOServiceService struct {
	mock.Mock
}

type mockOServiceService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockOServiceService) EXPECT() *mockOServiceService_Expecter {
	return &mockOServiceService_Expecter{mock: &_m.Mock}
}

// ClientOnline provides a mock function for the type mockOServiceService
func (_mock *mockOServiceService) ClientOnline(ctx context.Context, service uint16, bodyIn wire.SNAC_0x01_0x02_OServiceClientOnline, sess *state.Session) error {
	ret := _mock.Called(ctx, service, bodyIn, sess)

	if len(ret) == 0 {
		panic("no return value specified for ClientOnline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint16, wire.SNAC_0x01_0x02_OServiceClientOnline, *state.Session) error); ok {
		r0 = returnFunc(ctx, service, bodyIn, sess)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockOServiceService_ClientOnline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientOnline'
type mockOServiceService_ClientOnline_Call struct {
	*mock.Call
}

// ClientOnline is a helper method to define mock.On call
//   - ctx context.Context
//   - service uint16
//   - bodyIn wire.SNAC_0x01_0x02_OServiceClientOnline
//   - sess *state.Session
func (_e *mockOServiceService_Expecter) ClientOnline(ctx interface{}, service interface{}, bodyIn interface{}, sess interface{}) *mockOServiceService_ClientOnline_Call {
	return &mockOServiceService_ClientOnline_Call{Call: _e.mock.On("ClientOnline", ctx, service, bodyIn, sess)}
}

func (_c *mockOServiceService_ClientOnline_Call) Run(run func(ctx context.Context, service uint16, bodyIn wire.SNAC_0x01_0x02_OServiceClientOnline, sess *state.Session)) *mockOServiceService_ClientOnline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint16
		if args[1] != nil {
			arg1 = args[1].(uint16)
		}
		var arg2 wire.SNAC_0x01_0x02_OServiceClientOnline
		if args[2] != nil {
			arg2 = args[2].(wire.SNAC_0x01_0x02_OServiceClientOnline)
		}
		var arg3 *state.Session
		if args[3] != nil {
			arg3 = args[3].(*state.Session)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockOServiceService_ClientOnline_Call) Return(err error) *mockOServiceService_ClientOnline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockOServiceService_ClientOnline_Call) RunAndReturn(run func(ctx context.Context, service uint16, bodyIn wire.SNAC_0x01_0x02_OServiceClientOnline, sess *state.Session) error) *mockOServiceService_ClientOnline_Call {
	_c.Call.Return(run)
	return _c
}

// ClientVersions provides a mock function for the type mockOServiceService
func (_mock *mockOServiceService) ClientVersions(ctx context.Context, sess *state.Session, frame wire.SNACFrame, bodyIn wire.SNAC_0x01_0x17_OServiceClientVersions) wire.SNACMessage {
	ret := _mock.Called(ctx, sess, frame, bodyIn)

	if len(ret) == 0 {
		panic("no return value specified for ClientVersions")
	}

	var r0 wire.SNACMessage
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.Session, wire.SNACFrame, wire.SNAC_0x01_0x17_OServiceClientVersions) wire.SNACMessage); ok {
		r0 = returnFunc(ctx, sess, frame, bodyIn)
	} else {
		r0 = ret.Get(0).(wire.SNACMessage)
	}
	return r0
}

// mockOServiceService_ClientVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientVersions'
type mockOServiceService_ClientVersions_Call struct {
	*mock.Call
}

// ClientVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - sess *state.Session
//   - frame wire.SNACFrame
//   - bodyIn wire.SNAC_0x01_0x17_OServiceClientVersions
func (_e *mockOServiceService_Expecter) ClientVersions(ctx interface{}, sess interface{}, frame interface{}, bodyIn interface{}) *mockOServiceService_ClientVersions_Call {
	return &mockOServiceService_ClientVersions_Call{Call: _e.mock.On("ClientVersions", ctx, sess, frame, bodyIn)}
}

func (_c *mockOServiceService_ClientVersions_Call) Run(run func(ctx context.Context, sess *state.Session, frame wire.SNACFrame, bodyIn wire.SNAC_0x01_0x17_OServiceClientVersions)) *mockOServiceService_ClientVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.Session
		if args[1] != nil {
			arg1 = args[1].(*state.Session)
		}
		var arg2 wire.SNACFrame
		if args[2] != nil {
			arg2 = args[2].(wire.SNACFrame)
		}
		var arg3 wire.SNAC_0x01_0x17_OServiceClientVersions
		if args[3] != nil {
			arg3 = args[3].(wire.SNAC_0x01_0x17_OServiceClientVersions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockOServiceService_ClientVersions_Call) Return(sNACMessage wire.SNACMessage) *mockOServiceService_ClientVersions_Call {
	_c.Call.Return(sNACMessage)
	return _c
}

func (_c *mockOServiceService_ClientVersions_Call) RunAndReturn(run func(ctx context.Context, sess *state.Session, frame wire.SNACFrame, bodyIn wire.SNAC_0x01_0x17_OServiceClientVersions) wire.SNACMessage) *mockOServiceService_ClientVersions_Call {
	_c.Call.Return(run)
	return _c
}

// HostOnline provides a mock function for the type mockOServiceService
func (_mock *mockOServiceService) HostOnline(service uint16) wire.SNACMessage {
	ret := _mock.Called(service)

	if len(ret) == 0 {
		panic("no return value specified for HostOnline")
	}

	var r0 wire.SNACMessage
	if returnFunc, ok := ret.Get(0).(func(uint16) wire.SNACMessage); ok {
		r0 = returnFunc(service)
	} else {
		r0 = ret.Get(0).(wire.SNACMessage)
	}
	return r0
}

// mockOServiceService_HostOnline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HostOnline'
type mockOServiceService_HostOnline_Call struct {
	*mock.Call
}

// HostOnline is a helper method to define mock.On call
//   - service uint16
func (_e *mockOServiceService_Expecter) HostOnline(service interface{}) *mockOServiceService_HostOnline_Call {
	return &mockOServiceService_HostOnline_Call{Call: _e.mock.On("HostOnline", service)}
}

func (_c *mockOServiceService_HostOnline_Call) Run(run func(service uint16)) *mockOServiceService_HostOnline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint16
		if args[0] != nil {
			arg0 = args[0].(uint16)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockOServiceService_HostOnline_Call) Return(sNACMessage wire.SNACMessage) *mockOServiceService_HostOnline_Call {
	_c.Call.Return(sNACMessage)
	return _c
}

func (_c *mockOServiceService_HostOnline_Call) RunAndReturn(run func(service uint16) wire.SNACMessage) *mockOServiceService_HostOnline_Call {
	_c.Call.Return(run)
	return _c
}

// IdleNotification provides a mock function for the type mockOServiceService
func (_mock *mockOServiceService) IdleNotification(ctx context.Context, sess *state.Session, bodyIn wire.SNAC_0x01_0x11_OServiceIdleNotification) error {
	ret := _mock.Called(ctx, sess, bodyIn)

	if len(ret) == 0 {
		panic("no return value specified for IdleNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.Session, wire.SNAC_0x01_0x11_OServiceIdleNotification) error); ok {
		r0 = returnFunc(ctx, sess, bodyIn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockOServiceService_IdleNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IdleNotification'
type mockOServiceService_IdleNotification_Call struct {
	*mock.Call
}

// IdleNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - sess *state.Session
//   - bodyIn wire.SNAC_0x01_0x11_OServiceIdleNotification
func (_e *mockOServiceService_Expecter) IdleNotification(ctx interface{}, sess interface{}, bodyIn interface{}) *mockOServiceService_IdleNotification_Call {
	return &mockOServiceService_IdleNotification_Call{Call: _e.mock.On("IdleNotification", ctx, sess, bodyIn)}
}

func (_c *mockOServiceService_IdleNotification_Call) Run(run func(ctx context.Context, sess *state.Session, bodyIn wire.SNAC_0x01_0x11_OServiceIdleNotification)) *mockOServiceService_IdleNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.Session
		if args[1] != nil {
			arg1 = args[1].(*state.Session)
		}
		var arg2 wire.SNAC_0x01_0x11_OServiceIdleNotification
		if args[2] != nil {
			arg2 = args[2].(wire.SNAC_0x01_0x11_OServiceIdleNotification)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockOServiceService_IdleNotification_Call) Return(err error) *mockOServiceService_IdleNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockOServiceService_IdleNotification_Call) RunAndReturn(run func(ctx context.Context, sess *state.Session, bodyIn wire.SNAC_0x01_0x11_OServiceIdleNotification) error) *mockOServiceService_IdleNotification_Call {
	_c.Call.Return(run)
	return _c
}

// RateParamsQuery provides a mock function for the type mockOServiceService
func (_mock *mockOServiceService) RateParamsQuery(ctx context.Context, sess *state.Session, frame wire.SNACFrame) wire.SNACMessage {
	ret := _mock.Called(ctx, sess, frame)

	if len(ret) == 0 {
		panic("no return value specified for RateParamsQuery")
	}

	var r0 wire.SNACMessage
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.Session, wire.SNACFrame) wire.SNACMessage); ok {
		r0 = returnFunc(ctx, sess, frame)
	} else {
		r0 = ret.Get(0).(wire.SNACMessage)
	}
	return r0
}

// mockOServiceService_RateParamsQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RateParamsQuery'
type mockOServiceService_RateParamsQuery_Call struct {
	*mock.Call
}

// RateParamsQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - sess *state.Session
//   - frame wire.SNACFrame
func (_e *mockOServiceService_Expecter) RateParamsQuery(ctx interface{}, sess interface{}, frame interface{}) *mockOServiceService_RateParamsQuery_Call {
	return &mockOServiceService_RateParamsQuery_Call{Call: _e.mock.On("RateParamsQuery", ctx, sess, frame)}
}

func (_c *mockOServiceService_RateParamsQuery_Call) Run(run func(ctx context.Context, sess *state.Session, frame wire.SNACFrame)) *mockOServiceService_RateParamsQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.Session
		if args[1] != nil {
			arg1 = args[1].(*state.Session)
		}
		var arg2 wire.SNACFrame
		if args[2] != nil {
			arg2 = args[2].(wire.SNACFrame)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockOServiceService_RateParamsQuery_Call) Return(sNACMessage wire.SNACMessage) *mockOServiceService_RateParamsQuery_Call {
	_c.Call.Return(sNACMessage)
	return _c
}

func (_c *mockOServiceService_RateParamsQuery_Call) RunAndReturn(run func(ctx context.Context, sess *state.Session, frame wire.SNACFrame) wire.SNACMessage) *mockOServiceService_RateParamsQuery_Call {
	_c.Call.Return(run)
	return _c
}

// RateParamsSubAdd provides a mock function for the type mockOServiceService
func (_mock *mockOServiceService) RateParamsSubAdd(context1 context.Context, session *state.Session, sNAC_0x01_0x08_OServiceRateParamsSubAdd wire.SNAC_0x01_0x08_OServiceRateParamsSubAdd) {
	_mock.Called(context1, session, sNAC_0x01_0x08_OServiceRateParamsSubAdd)
	return
}

// mockOServiceService_RateParamsSubAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RateParamsSubAdd'
type mockOServiceService_RateParamsSubAdd_Call struct {
	*mock.Call
}

// RateParamsSubAdd is a helper method to define mock.On call
//   - context1 context.Context
//   - session *state.Session
//   - sNAC_0x01_0x08_OServiceRateParamsSubAdd wire.SNAC_0x01_0x08_OServiceRateParamsSubAdd
func (_e *mockOServiceService_Expecter) RateParamsSubAdd(context1 interface{}, session interface{}, sNAC_0x01_0x08_OServiceRateParamsSubAdd interface{}) *mockOServiceService_RateParamsSubAdd_Call {
	return &mockOServiceService_RateParamsSubAdd_Call{Call: _e.mock.On("RateParamsSubAdd", context1, session, sNAC_0x01_0x08_OServiceRateParamsSubAdd)}
}

func (_c *mockOServiceService_RateParamsSubAdd_Call) Run(run func(context1 context.Context, session *state.Session, sNAC_0x01_0x08_OServiceRateParamsSubAdd wire.SNAC_0x01_0x08_OServiceRateParamsSubAdd)) *mockOServiceService_RateParamsSubAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.Session
		if args[1] != nil {
			arg1 = args[1].(*state.Session)
		}
		var arg2 wire.SNAC_0x01_0x08_OServiceRateParamsSubAdd
		if args[2] != nil {
			arg2 = args[2].(wire.SNAC_0x01_0x08_OServiceRateParamsSubAdd)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockOServiceService_RateParamsSubAdd_Call) Return() *mockOServiceService_RateParamsSubAdd_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockOServiceService_RateParamsSubAdd_Call) RunAndReturn(run func(context1 context.Context, session *state.Session, sNAC_0x01_0x08_OServiceRateParamsSubAdd wire.SNAC_0x01_0x08_OServiceRateParamsSubAdd)) *mockOServiceService_RateParamsSubAdd_Call {
	_c.Run(run)
	return _c
}

// ServiceRequest provides a mock function for the type mockOServiceService
func (_mock *mockOServiceService) ServiceRequest(ctx context.Context, service uint16, sess *state.Session, frame wire.SNACFrame, bodyIn wire.SNAC_0x01_0x04_OServiceServiceRequest, advertisedHost config.Listener) (wire.SNACMessage, error) {
	ret := _mock.Called(ctx, service, sess, frame, bodyIn, advertisedHost)

	if len(ret) == 0 {
		panic("no return value specified for ServiceRequest")
	}

	var r0 wire.SNACMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint16, *state.Session, wire.SNACFrame, wire.SNAC_0x01_0x04_OServiceServiceRequest, config.Listener) (wire.SNACMessage, error)); ok {
		return returnFunc(ctx, service, sess, frame, bodyIn, advertisedHost)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint16, *state.Session, wire.SNACFrame, wire.SNAC_0x01_0x04_OServiceServiceRequest, config.Listener) wire.SNACMessage); ok {
		r0 = returnFunc(ctx, service, sess, frame, bodyIn, advertisedHost)
	} else {
		r0 = ret.Get(0).(wire.SNACMessage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint16, *state.Session, wire.SNACFrame, wire.SNAC_0x01_0x04_OServiceServiceRequest, config.Listener) error); ok {
		r1 = returnFunc(ctx, service, sess, frame, bodyIn, advertisedHost)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockOServiceService_ServiceRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceRequest'
type mockOServiceService_ServiceRequest_Call struct {
	*mock.Call
}

// ServiceRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - service uint16
//   - sess *state.Session
//   - frame wire.SNACFrame
//   - bodyIn wire.SNAC_0x01_0x04_OServiceServiceRequest
//   - advertisedHost config.Listener
func (_e *mockOServiceService_Expecter) ServiceRequest(ctx interface{}, service interface{}, sess interface{}, frame interface{}, bodyIn interface{}, advertisedHost interface{}) *mockOServiceService_ServiceRequest_Call {
	return &mockOServiceService_ServiceRequest_Call{Call: _e.mock.On("ServiceRequest", ctx, service, sess, frame, bodyIn, advertisedHost)}
}

func (_c *mockOServiceService_ServiceRequest_Call) Run(run func(ctx context.Context, service uint16, sess *state.Session, frame wire.SNACFrame, bodyIn wire.SNAC_0x01_0x04_OServiceServiceRequest, advertisedHost config.Listener)) *mockOServiceService_ServiceRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint16
		if args[1] != nil {
			arg1 = args[1].(uint16)
		}
		var arg2 *state.Session
		if args[2] != nil {
			arg2 = args[2].(*state.Session)
		}
		var arg3 wire.SNACFrame
		if args[3] != nil {
			arg3 = args[3].(wire.SNACFrame)
		}
		var arg4 wire.SNAC_0x01_0x04_OServiceServiceRequest
		if args[4] != nil {
			arg4 = args[4].(wire.SNAC_0x01_0x04_OServiceServiceRequest)
		}
		var arg5 config.Listener
		if args[5] != nil {
			arg5 = args[5].(config.Listener)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *mockOServiceService_ServiceRequest_Call) Return(sNACMessage wire.SNACMessage, err error) *mockOServiceService_ServiceRequest_Call {
	_c.Call.Return(sNACMessage, err)
	return _c
}

func (_c *mockOServiceService_ServiceRequest_Call) RunAndReturn(run func(ctx context.Context, service uint16, sess *state.Session, frame wire.SNACFrame, bodyIn wire.SNAC_0x01_0x04_OServiceServiceRequest, advertisedHost config.Listener) (wire.SNACMessage, error)) *mockOServiceService_ServiceRequest_Call {
	_c.Call.Return(run)
	return _c
}

// SetPrivacyFlags provides a mock function for the type mockOServiceService
func (_mock *mockOServiceService) SetPrivacyFlags(ctx context.Context, bodyIn wire.SNAC_0x01_0x14_OServiceSetPrivacyFlags) {
	_mock.Called(ctx, bodyIn)
	return
}

// mockOServiceService_SetPrivacyFlags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPrivacyFlags'
type mockOServiceService_SetPrivacyFlags_Call struct {
	*mock.Call
}

// SetPrivacyFlags is a helper method to define mock.On call
//   - ctx context.Context
//   - bodyIn wire.SNAC_0x01_0x14_OServiceSetPrivacyFlags
func (_e *mockOServiceService_Expecter) SetPrivacyFlags(ctx interface{}, bodyIn interface{}) *mockOServiceService_SetPrivacyFlags_Call {
	return &mockOServiceService_SetPrivacyFlags_Call{Call: _e.mock.On("SetPrivacyFlags", ctx, bodyIn)}
}

func (_c *mockOServiceService_SetPrivacyFlags_Call) Run(run func(ctx context.Context, bodyIn wire.SNAC_0x01_0x14_OServiceSetPrivacyFlags)) *mockOServiceService_SetPrivacyFlags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 wire.SNAC_0x01_0x14_OServiceSetPrivacyFlags
		if args[1] != nil {
			arg1 = args[1].(wire.SNAC_0x01_0x14_OServiceSetPrivacyFlags)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockOServiceService_SetPrivacyFlags_Call) Return() *mockOServiceService_SetPrivacyFlags_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockOServiceService_SetPrivacyFlags_Call) RunAndReturn(run func(ctx context.Context, bodyIn wire.SNAC_0x01_0x14_OServiceSetPrivacyFlags)) *mockOServiceService_SetPrivacyFlags_Call {
	_c.Run(run)
	return _c
}

// SetUserInfoFields provides a mock function for the type mockOServiceService
func (_mock *mockOServiceService) SetUserInfoFields(ctx context.Context, sess *state.Session, frame wire.SNACFrame, bodyIn wire.SNAC_0x01_0x1E_OServiceSetUserInfoFields) (wire.SNACMessage, error) {
	ret := _mock.Called(ctx, sess, frame, bodyIn)

	if len(ret) == 0 {
		panic("no return value specified for SetUserInfoFields")
	}

	var r0 wire.SNACMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.Session, wire.SNACFrame, wire.SNAC_0x01_0x1E_OServiceSetUserInfoFields) (wire.SNACMessage, error)); ok {
		return returnFunc(ctx, sess, frame, bodyIn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.Session, wire.SNACFrame, wire.SNAC_0x01_0x1E_OServiceSetUserInfoFields) wire.SNACMessage); ok {
		r0 = returnFunc(ctx, sess, frame, bodyIn)
	} else {
		r0 = ret.Get(0).(wire.SNACMessage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *state.Session, wire.SNACFrame, wire.SNAC_0x01_0x1E_OServiceSetUserInfoFields) error); ok {
		r1 = returnFunc(ctx, sess, frame, bodyIn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockOServiceService_SetUserInfoFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserInfoFields'
type mockOServiceService_SetUserInfoFields_Call struct {
	*mock.Call
}

// SetUserInfoFields is a helper method to define mock.On call
//   - ctx context.Context
//   - sess *state.Session
//   - frame wire.SNACFrame
//   - bodyIn wire.SNAC_0x01_0x1E_OServiceSetUserInfoFields
func (_e *mockOServiceService_Expecter) SetUserInfoFields(ctx interface{}, sess interface{}, frame interface{}, bodyIn interface{}) *mockOServiceService_SetUserInfoFields_Call {
	return &mockOServiceService_SetUserInfoFields_Call{Call: _e.mock.On("SetUserInfoFields", ctx, sess, frame, bodyIn)}
}

func (_c *mockOServiceService_SetUserInfoFields_Call) Run(run func(ctx context.Context, sess *state.Session, frame wire.SNACFrame, bodyIn wire.SNAC_0x01_0x1E_OServiceSetUserInfoFields)) *mockOServiceService_SetUserInfoFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.Session
		if args[1] != nil {
			arg1 = args[1].(*state.Session)
		}
		var arg2 wire.SNACFrame
		if args[2] != nil {
			arg2 = args[2].(wire.SNACFrame)
		}
		var arg3 wire.SNAC_0x01_0x1E_OServiceSetUserInfoFields
		if args[3] != nil {
			arg3 = args[3].(wire.SNAC_0x01_0x1E_OServiceSetUserInfoFields)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockOServiceService_SetUserInfoFields_Call) Return(sNACMessage wire.SNACMessage, err error) *mockOServiceService_SetUserInfoFields_Call {
	_c.Call.Return(sNACMessage, err)
	return _c
}

func (_c *mockOServiceService_SetUserInfoFields_Call) RunAndReturn(run func(ctx context.Context, sess *state.Session, frame wire.SNACFrame, bodyIn wire.SNAC_0x01_0x1E_OServiceSetUserInfoFields) (wire.SNACMessage, error)) *mockOServiceService_SetUserInfoFields_Call {
	_c.Call.Return(run)
	return _c
}

// UserInfoQuery provides a mock function for the type mockOServiceService
func (_mock *mockOServiceService) UserInfoQuery(ctx context.Context, sess *state.Session, frame wire.SNACFrame) wire.SNACMessage {
	ret := _mock.Called(ctx, sess, frame)

	if len(ret) == 0 {
		panic("no return value specified for UserInfoQuery")
	}

	var r0 wire.SNACMessage
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.Session, wire.SNACFrame) wire.SNACMessage); ok {
		r0 = returnFunc(ctx, sess, frame)
	} else {
		r0 = ret.Get(0).(wire.SNACMessage)
	}
	return r0
}

// mockOServiceService_UserInfoQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserInfoQuery'
type mockOServiceService_UserInfoQuery_Call struct {
	*mock.Call
}

// UserInfoQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - sess *state.Session
//   - frame wire.SNACFrame
func (_e *mockOServiceService_Expecter) UserInfoQuery(ctx interface{}, sess interface{}, frame interface{}) *mockOServiceService_UserInfoQuery_Call {
	return &mockOServiceService_UserInfoQuery_Call{Call: _e.mock.On("UserInfoQuery", ctx, sess, frame)}
}

func (_c *mockOServiceService_UserInfoQuery_Call) Run(run func(ctx context.Context, sess *state.Session, frame wire.SNACFrame)) *mockOServiceService_UserInfoQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.Session
		if args[1] != nil {
			arg1 = args[1].(*state.Session)
		}
		var arg2 wire.SNACFrame
		if args[2] != nil {
			arg2 = args[2].(wire.SNACFrame)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockOServiceService_UserInfoQuery_Call) Return(sNACMessage wire.SNACMessage) *mockOServiceService_UserInfoQuery_Call {
	_c.Call.Return(sNACMessage)
	return _c
}

func (_c *mockOServiceService_UserInfoQuery_Call) RunAndReturn(run func(ctx context.Context, sess *state.Session, frame wire.SNACFrame) wire.SNACMessage) *mockOServiceService_UserInfoQuery_Call {
	_c.Call.Return(run)
	return _c
}
