// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package icq_legacy

import (
	"context"

	"github.com/mk6i/open-oscar-server/state"
	"github.com/mk6i/open-oscar-server/wire"
	mock "github.com/stretchr/testify/mock"
)

// newMockBuddyService creates a new instance of mockBuddyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBuddyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBuddyService {
	mock := &mockBuddyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockBuddyService is an autogenerated mock type for the BuddyService type
type mockBuddyService struct {
	mock.Mock
}

type mockBuddyService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockBuddyService) EXPECT() *mockBuddyService_Expecter {
	return &mockBuddyService_Expecter{mock: &_m.Mock}
}

// AddBuddies provides a mock function for the type mockBuddyService
func (_mock *mockBuddyService) AddBuddies(ctx context.Context, instance *state.SessionInstance, inFrame wire.SNACFrame, inBody wire.SNAC_0x03_0x04_BuddyAddBuddies) (*wire.SNACMessage, error) {
	ret := _mock.Called(ctx, instance, inFrame, inBody)

	if len(ret) == 0 {
		panic("no return value specified for AddBuddies")
	}

	var r0 *wire.SNACMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance, wire.SNACFrame, wire.SNAC_0x03_0x04_BuddyAddBuddies) (*wire.SNACMessage, error)); ok {
		return returnFunc(ctx, instance, inFrame, inBody)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance, wire.SNACFrame, wire.SNAC_0x03_0x04_BuddyAddBuddies) *wire.SNACMessage); ok {
		r0 = returnFunc(ctx, instance, inFrame, inBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wire.SNACMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *state.SessionInstance, wire.SNACFrame, wire.SNAC_0x03_0x04_BuddyAddBuddies) error); ok {
		r1 = returnFunc(ctx, instance, inFrame, inBody)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockBuddyService_AddBuddies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBuddies'
type mockBuddyService_AddBuddies_Call struct {
	*mock.Call
}

// AddBuddies is a helper method to define mock.On call
//   - ctx context.Context
//   - instance *state.SessionInstance
//   - inFrame wire.SNACFrame
//   - inBody wire.SNAC_0x03_0x04_BuddyAddBuddies
func (_e *mockBuddyService_Expecter) AddBuddies(ctx interface{}, instance interface{}, inFrame interface{}, inBody interface{}) *mockBuddyService_AddBuddies_Call {
	return &mockBuddyService_AddBuddies_Call{Call: _e.mock.On("AddBuddies", ctx, instance, inFrame, inBody)}
}

func (_c *mockBuddyService_AddBuddies_Call) Run(run func(ctx context.Context, instance *state.SessionInstance, inFrame wire.SNACFrame, inBody wire.SNAC_0x03_0x04_BuddyAddBuddies)) *mockBuddyService_AddBuddies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.SessionInstance
		if args[1] != nil {
			arg1 = args[1].(*state.SessionInstance)
		}
		var arg2 wire.SNACFrame
		if args[2] != nil {
			arg2 = args[2].(wire.SNACFrame)
		}
		var arg3 wire.SNAC_0x03_0x04_BuddyAddBuddies
		if args[3] != nil {
			arg3 = args[3].(wire.SNAC_0x03_0x04_BuddyAddBuddies)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockBuddyService_AddBuddies_Call) Return(sNACMessage *wire.SNACMessage, err error) *mockBuddyService_AddBuddies_Call {
	_c.Call.Return(sNACMessage, err)
	return _c
}

func (_c *mockBuddyService_AddBuddies_Call) RunAndReturn(run func(ctx context.Context, instance *state.SessionInstance, inFrame wire.SNACFrame, inBody wire.SNAC_0x03_0x04_BuddyAddBuddies) (*wire.SNACMessage, error)) *mockBuddyService_AddBuddies_Call {
	_c.Call.Return(run)
	return _c
}
