// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package icq_legacy

import (
	"net"

	mock "github.com/stretchr/testify/mock"
)

// newMockPacketSender creates a new instance of mockPacketSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPacketSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPacketSender {
	mock := &mockPacketSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockPacketSender is an autogenerated mock type for the PacketSender type
type mockPacketSender struct {
	mock.Mock
}

type mockPacketSender_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPacketSender) EXPECT() *mockPacketSender_Expecter {
	return &mockPacketSender_Expecter{mock: &_m.Mock}
}

// SendPacket provides a mock function for the type mockPacketSender
func (_mock *mockPacketSender) SendPacket(addr *net.UDPAddr, packet []byte) error {
	ret := _mock.Called(addr, packet)

	if len(ret) == 0 {
		panic("no return value specified for SendPacket")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*net.UDPAddr, []byte) error); ok {
		r0 = returnFunc(addr, packet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockPacketSender_SendPacket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPacket'
type mockPacketSender_SendPacket_Call struct {
	*mock.Call
}

// SendPacket is a helper method to define mock.On call
//   - addr *net.UDPAddr
//   - packet []byte
func (_e *mockPacketSender_Expecter) SendPacket(addr interface{}, packet interface{}) *mockPacketSender_SendPacket_Call {
	return &mockPacketSender_SendPacket_Call{Call: _e.mock.On("SendPacket", addr, packet)}
}

func (_c *mockPacketSender_SendPacket_Call) Run(run func(addr *net.UDPAddr, packet []byte)) *mockPacketSender_SendPacket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *net.UDPAddr
		if args[0] != nil {
			arg0 = args[0].(*net.UDPAddr)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockPacketSender_SendPacket_Call) Return(err error) *mockPacketSender_SendPacket_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockPacketSender_SendPacket_Call) RunAndReturn(run func(addr *net.UDPAddr, packet []byte) error) *mockPacketSender_SendPacket_Call {
	_c.Call.Return(run)
	return _c
}

// SendToSession provides a mock function for the type mockPacketSender
func (_mock *mockPacketSender) SendToSession(session *LegacySession, packet []byte) error {
	ret := _mock.Called(session, packet)

	if len(ret) == 0 {
		panic("no return value specified for SendToSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*LegacySession, []byte) error); ok {
		r0 = returnFunc(session, packet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockPacketSender_SendToSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendToSession'
type mockPacketSender_SendToSession_Call struct {
	*mock.Call
}

// SendToSession is a helper method to define mock.On call
//   - session *LegacySession
//   - packet []byte
func (_e *mockPacketSender_Expecter) SendToSession(session interface{}, packet interface{}) *mockPacketSender_SendToSession_Call {
	return &mockPacketSender_SendToSession_Call{Call: _e.mock.On("SendToSession", session, packet)}
}

func (_c *mockPacketSender_SendToSession_Call) Run(run func(session *LegacySession, packet []byte)) *mockPacketSender_SendToSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *LegacySession
		if args[0] != nil {
			arg0 = args[0].(*LegacySession)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockPacketSender_SendToSession_Call) Return(err error) *mockPacketSender_SendToSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockPacketSender_SendToSession_Call) RunAndReturn(run func(session *LegacySession, packet []byte) error) *mockPacketSender_SendToSession_Call {
	_c.Call.Return(run)
	return _c
}
