// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package icq_legacy

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockMessageDispatcher creates a new instance of mockMessageDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMessageDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMessageDispatcher {
	mock := &mockMessageDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockMessageDispatcher is an autogenerated mock type for the MessageDispatcher type
type mockMessageDispatcher struct {
	mock.Mock
}

type mockMessageDispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockMessageDispatcher) EXPECT() *mockMessageDispatcher_Expecter {
	return &mockMessageDispatcher_Expecter{mock: &_m.Mock}
}

// SendOnlineMessage provides a mock function for the type mockMessageDispatcher
func (_mock *mockMessageDispatcher) SendOnlineMessage(toSession *LegacySession, fromUIN uint32, msgType uint16, message string) error {
	ret := _mock.Called(toSession, fromUIN, msgType, message)

	if len(ret) == 0 {
		panic("no return value specified for SendOnlineMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*LegacySession, uint32, uint16, string) error); ok {
		r0 = returnFunc(toSession, fromUIN, msgType, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockMessageDispatcher_SendOnlineMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOnlineMessage'
type mockMessageDispatcher_SendOnlineMessage_Call struct {
	*mock.Call
}

// SendOnlineMessage is a helper method to define mock.On call
//   - toSession *LegacySession
//   - fromUIN uint32
//   - msgType uint16
//   - message string
func (_e *mockMessageDispatcher_Expecter) SendOnlineMessage(toSession interface{}, fromUIN interface{}, msgType interface{}, message interface{}) *mockMessageDispatcher_SendOnlineMessage_Call {
	return &mockMessageDispatcher_SendOnlineMessage_Call{Call: _e.mock.On("SendOnlineMessage", toSession, fromUIN, msgType, message)}
}

func (_c *mockMessageDispatcher_SendOnlineMessage_Call) Run(run func(toSession *LegacySession, fromUIN uint32, msgType uint16, message string)) *mockMessageDispatcher_SendOnlineMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *LegacySession
		if args[0] != nil {
			arg0 = args[0].(*LegacySession)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockMessageDispatcher_SendOnlineMessage_Call) Return(err error) *mockMessageDispatcher_SendOnlineMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockMessageDispatcher_SendOnlineMessage_Call) RunAndReturn(run func(toSession *LegacySession, fromUIN uint32, msgType uint16, message string) error) *mockMessageDispatcher_SendOnlineMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendStatusChange provides a mock function for the type mockMessageDispatcher
func (_mock *mockMessageDispatcher) SendStatusChange(toSession *LegacySession, changedUIN uint32, newStatus uint32) error {
	ret := _mock.Called(toSession, changedUIN, newStatus)

	if len(ret) == 0 {
		panic("no return value specified for SendStatusChange")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*LegacySession, uint32, uint32) error); ok {
		r0 = returnFunc(toSession, changedUIN, newStatus)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockMessageDispatcher_SendStatusChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendStatusChange'
type mockMessageDispatcher_SendStatusChange_Call struct {
	*mock.Call
}

// SendStatusChange is a helper method to define mock.On call
//   - toSession *LegacySession
//   - changedUIN uint32
//   - newStatus uint32
func (_e *mockMessageDispatcher_Expecter) SendStatusChange(toSession interface{}, changedUIN interface{}, newStatus interface{}) *mockMessageDispatcher_SendStatusChange_Call {
	return &mockMessageDispatcher_SendStatusChange_Call{Call: _e.mock.On("SendStatusChange", toSession, changedUIN, newStatus)}
}

func (_c *mockMessageDispatcher_SendStatusChange_Call) Run(run func(toSession *LegacySession, changedUIN uint32, newStatus uint32)) *mockMessageDispatcher_SendStatusChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *LegacySession
		if args[0] != nil {
			arg0 = args[0].(*LegacySession)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		var arg2 uint32
		if args[2] != nil {
			arg2 = args[2].(uint32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockMessageDispatcher_SendStatusChange_Call) Return(err error) *mockMessageDispatcher_SendStatusChange_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockMessageDispatcher_SendStatusChange_Call) RunAndReturn(run func(toSession *LegacySession, changedUIN uint32, newStatus uint32) error) *mockMessageDispatcher_SendStatusChange_Call {
	_c.Call.Return(run)
	return _c
}

// SendUserOffline provides a mock function for the type mockMessageDispatcher
func (_mock *mockMessageDispatcher) SendUserOffline(toSession *LegacySession, offlineUIN uint32) error {
	ret := _mock.Called(toSession, offlineUIN)

	if len(ret) == 0 {
		panic("no return value specified for SendUserOffline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*LegacySession, uint32) error); ok {
		r0 = returnFunc(toSession, offlineUIN)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockMessageDispatcher_SendUserOffline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendUserOffline'
type mockMessageDispatcher_SendUserOffline_Call struct {
	*mock.Call
}

// SendUserOffline is a helper method to define mock.On call
//   - toSession *LegacySession
//   - offlineUIN uint32
func (_e *mockMessageDispatcher_Expecter) SendUserOffline(toSession interface{}, offlineUIN interface{}) *mockMessageDispatcher_SendUserOffline_Call {
	return &mockMessageDispatcher_SendUserOffline_Call{Call: _e.mock.On("SendUserOffline", toSession, offlineUIN)}
}

func (_c *mockMessageDispatcher_SendUserOffline_Call) Run(run func(toSession *LegacySession, offlineUIN uint32)) *mockMessageDispatcher_SendUserOffline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *LegacySession
		if args[0] != nil {
			arg0 = args[0].(*LegacySession)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockMessageDispatcher_SendUserOffline_Call) Return(err error) *mockMessageDispatcher_SendUserOffline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockMessageDispatcher_SendUserOffline_Call) RunAndReturn(run func(toSession *LegacySession, offlineUIN uint32) error) *mockMessageDispatcher_SendUserOffline_Call {
	_c.Call.Return(run)
	return _c
}

// SendUserOnline provides a mock function for the type mockMessageDispatcher
func (_mock *mockMessageDispatcher) SendUserOnline(toSession *LegacySession, onlineUIN uint32, status uint32) error {
	ret := _mock.Called(toSession, onlineUIN, status)

	if len(ret) == 0 {
		panic("no return value specified for SendUserOnline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*LegacySession, uint32, uint32) error); ok {
		r0 = returnFunc(toSession, onlineUIN, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockMessageDispatcher_SendUserOnline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendUserOnline'
type mockMessageDispatcher_SendUserOnline_Call struct {
	*mock.Call
}

// SendUserOnline is a helper method to define mock.On call
//   - toSession *LegacySession
//   - onlineUIN uint32
//   - status uint32
func (_e *mockMessageDispatcher_Expecter) SendUserOnline(toSession interface{}, onlineUIN interface{}, status interface{}) *mockMessageDispatcher_SendUserOnline_Call {
	return &mockMessageDispatcher_SendUserOnline_Call{Call: _e.mock.On("SendUserOnline", toSession, onlineUIN, status)}
}

func (_c *mockMessageDispatcher_SendUserOnline_Call) Run(run func(toSession *LegacySession, onlineUIN uint32, status uint32)) *mockMessageDispatcher_SendUserOnline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *LegacySession
		if args[0] != nil {
			arg0 = args[0].(*LegacySession)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		var arg2 uint32
		if args[2] != nil {
			arg2 = args[2].(uint32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockMessageDispatcher_SendUserOnline_Call) Return(err error) *mockMessageDispatcher_SendUserOnline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockMessageDispatcher_SendUserOnline_Call) RunAndReturn(run func(toSession *LegacySession, onlineUIN uint32, status uint32) error) *mockMessageDispatcher_SendUserOnline_Call {
	_c.Call.Return(run)
	return _c
}
