// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package icq_legacy

import (
	"context"

	"github.com/mk6i/open-oscar-server/state"
	mock "github.com/stretchr/testify/mock"
)

// newMockClientSideBuddyListManager creates a new instance of mockClientSideBuddyListManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockClientSideBuddyListManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockClientSideBuddyListManager {
	mock := &mockClientSideBuddyListManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockClientSideBuddyListManager is an autogenerated mock type for the ClientSideBuddyListManager type
type mockClientSideBuddyListManager struct {
	mock.Mock
}

type mockClientSideBuddyListManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockClientSideBuddyListManager) EXPECT() *mockClientSideBuddyListManager_Expecter {
	return &mockClientSideBuddyListManager_Expecter{mock: &_m.Mock}
}

// AddBuddy provides a mock function for the type mockClientSideBuddyListManager
func (_mock *mockClientSideBuddyListManager) AddBuddy(ctx context.Context, me state.IdentScreenName, them state.IdentScreenName) error {
	ret := _mock.Called(ctx, me, them)

	if len(ret) == 0 {
		panic("no return value specified for AddBuddy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, state.IdentScreenName) error); ok {
		r0 = returnFunc(ctx, me, them)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockClientSideBuddyListManager_AddBuddy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBuddy'
type mockClientSideBuddyListManager_AddBuddy_Call struct {
	*mock.Call
}

// AddBuddy is a helper method to define mock.On call
//   - ctx context.Context
//   - me state.IdentScreenName
//   - them state.IdentScreenName
func (_e *mockClientSideBuddyListManager_Expecter) AddBuddy(ctx interface{}, me interface{}, them interface{}) *mockClientSideBuddyListManager_AddBuddy_Call {
	return &mockClientSideBuddyListManager_AddBuddy_Call{Call: _e.mock.On("AddBuddy", ctx, me, them)}
}

func (_c *mockClientSideBuddyListManager_AddBuddy_Call) Run(run func(ctx context.Context, me state.IdentScreenName, them state.IdentScreenName)) *mockClientSideBuddyListManager_AddBuddy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		var arg2 state.IdentScreenName
		if args[2] != nil {
			arg2 = args[2].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockClientSideBuddyListManager_AddBuddy_Call) Return(err error) *mockClientSideBuddyListManager_AddBuddy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockClientSideBuddyListManager_AddBuddy_Call) RunAndReturn(run func(ctx context.Context, me state.IdentScreenName, them state.IdentScreenName) error) *mockClientSideBuddyListManager_AddBuddy_Call {
	_c.Call.Return(run)
	return _c
}
