// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package icq_legacy

import (
	"context"

	"github.com/mk6i/open-oscar-server/state"
	mock "github.com/stretchr/testify/mock"
)

// newMockAccountManager creates a new instance of mockAccountManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAccountManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAccountManager {
	mock := &mockAccountManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockAccountManager is an autogenerated mock type for the AccountManager type
type mockAccountManager struct {
	mock.Mock
}

type mockAccountManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAccountManager) EXPECT() *mockAccountManager_Expecter {
	return &mockAccountManager_Expecter{mock: &_m.Mock}
}

// SetUserPassword provides a mock function for the type mockAccountManager
func (_mock *mockAccountManager) SetUserPassword(ctx context.Context, screenName state.IdentScreenName, newPassword string) error {
	ret := _mock.Called(ctx, screenName, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for SetUserPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, string) error); ok {
		r0 = returnFunc(ctx, screenName, newPassword)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockAccountManager_SetUserPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserPassword'
type mockAccountManager_SetUserPassword_Call struct {
	*mock.Call
}

// SetUserPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
//   - newPassword string
func (_e *mockAccountManager_Expecter) SetUserPassword(ctx interface{}, screenName interface{}, newPassword interface{}) *mockAccountManager_SetUserPassword_Call {
	return &mockAccountManager_SetUserPassword_Call{Call: _e.mock.On("SetUserPassword", ctx, screenName, newPassword)}
}

func (_c *mockAccountManager_SetUserPassword_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName, newPassword string)) *mockAccountManager_SetUserPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAccountManager_SetUserPassword_Call) Return(err error) *mockAccountManager_SetUserPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockAccountManager_SetUserPassword_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName, newPassword string) error) *mockAccountManager_SetUserPassword_Call {
	_c.Call.Return(run)
	return _c
}
