// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package foodgroup

import (
	"context"

	"github.com/mk6i/open-oscar-server/state"
	mock "github.com/stretchr/testify/mock"
)

// newMockContactPreAuthorizer creates a new instance of mockContactPreAuthorizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockContactPreAuthorizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockContactPreAuthorizer {
	mock := &mockContactPreAuthorizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockContactPreAuthorizer is an autogenerated mock type for the ContactPreAuthorizer type
type mockContactPreAuthorizer struct {
	mock.Mock
}

type mockContactPreAuthorizer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockContactPreAuthorizer) EXPECT() *mockContactPreAuthorizer_Expecter {
	return &mockContactPreAuthorizer_Expecter{mock: &_m.Mock}
}

// RecordPreAuth provides a mock function for the type mockContactPreAuthorizer
func (_mock *mockContactPreAuthorizer) RecordPreAuth(ctx context.Context, owner state.IdentScreenName, requester state.IdentScreenName) error {
	ret := _mock.Called(ctx, owner, requester)

	if len(ret) == 0 {
		panic("no return value specified for RecordPreAuth")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, state.IdentScreenName) error); ok {
		r0 = returnFunc(ctx, owner, requester)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockContactPreAuthorizer_RecordPreAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordPreAuth'
type mockContactPreAuthorizer_RecordPreAuth_Call struct {
	*mock.Call
}

// RecordPreAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - owner state.IdentScreenName
//   - requester state.IdentScreenName
func (_e *mockContactPreAuthorizer_Expecter) RecordPreAuth(ctx interface{}, owner interface{}, requester interface{}) *mockContactPreAuthorizer_RecordPreAuth_Call {
	return &mockContactPreAuthorizer_RecordPreAuth_Call{Call: _e.mock.On("RecordPreAuth", ctx, owner, requester)}
}

func (_c *mockContactPreAuthorizer_RecordPreAuth_Call) Run(run func(ctx context.Context, owner state.IdentScreenName, requester state.IdentScreenName)) *mockContactPreAuthorizer_RecordPreAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		var arg2 state.IdentScreenName
		if args[2] != nil {
			arg2 = args[2].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockContactPreAuthorizer_RecordPreAuth_Call) Return(err error) *mockContactPreAuthorizer_RecordPreAuth_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockContactPreAuthorizer_RecordPreAuth_Call) RunAndReturn(run func(ctx context.Context, owner state.IdentScreenName, requester state.IdentScreenName) error) *mockContactPreAuthorizer_RecordPreAuth_Call {
	_c.Call.Return(run)
	return _c
}

// RequiresAuthorization provides a mock function for the type mockContactPreAuthorizer
func (_mock *mockContactPreAuthorizer) RequiresAuthorization(ctx context.Context, owner state.IdentScreenName, requester state.IdentScreenName) (bool, error) {
	ret := _mock.Called(ctx, owner, requester)

	if len(ret) == 0 {
		panic("no return value specified for RequiresAuthorization")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, state.IdentScreenName) (bool, error)); ok {
		return returnFunc(ctx, owner, requester)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, state.IdentScreenName) bool); ok {
		r0 = returnFunc(ctx, owner, requester)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.IdentScreenName, state.IdentScreenName) error); ok {
		r1 = returnFunc(ctx, owner, requester)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockContactPreAuthorizer_RequiresAuthorization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequiresAuthorization'
type mockContactPreAuthorizer_RequiresAuthorization_Call struct {
	*mock.Call
}

// RequiresAuthorization is a helper method to define mock.On call
//   - ctx context.Context
//   - owner state.IdentScreenName
//   - requester state.IdentScreenName
func (_e *mockContactPreAuthorizer_Expecter) RequiresAuthorization(ctx interface{}, owner interface{}, requester interface{}) *mockContactPreAuthorizer_RequiresAuthorization_Call {
	return &mockContactPreAuthorizer_RequiresAuthorization_Call{Call: _e.mock.On("RequiresAuthorization", ctx, owner, requester)}
}

func (_c *mockContactPreAuthorizer_RequiresAuthorization_Call) Run(run func(ctx context.Context, owner state.IdentScreenName, requester state.IdentScreenName)) *mockContactPreAuthorizer_RequiresAuthorization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		var arg2 state.IdentScreenName
		if args[2] != nil {
			arg2 = args[2].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockContactPreAuthorizer_RequiresAuthorization_Call) Return(b bool, err error) *mockContactPreAuthorizer_RequiresAuthorization_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockContactPreAuthorizer_RequiresAuthorization_Call) RunAndReturn(run func(ctx context.Context, owner state.IdentScreenName, requester state.IdentScreenName) (bool, error)) *mockContactPreAuthorizer_RequiresAuthorization_Call {
	_c.Call.Return(run)
	return _c
}
