// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package foodgroup

import (
	"context"

	"github.com/mk6i/open-oscar-server/state"
	mock "github.com/stretchr/testify/mock"
)

// newMockSessionRegistry creates a new instance of mockSessionRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSessionRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSessionRegistry {
	mock := &mockSessionRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockSessionRegistry is an autogenerated mock type for the SessionRegistry type
type mockSessionRegistry struct {
	mock.Mock
}

type mockSessionRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSessionRegistry) EXPECT() *mockSessionRegistry_Expecter {
	return &mockSessionRegistry_Expecter{mock: &_m.Mock}
}

// AddSession provides a mock function for the type mockSessionRegistry
func (_mock *mockSessionRegistry) AddSession(ctx context.Context, screenName state.DisplayScreenName) (*state.Session, error) {
	ret := _mock.Called(ctx, screenName)

	if len(ret) == 0 {
		panic("no return value specified for AddSession")
	}

	var r0 *state.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.DisplayScreenName) (*state.Session, error)); ok {
		return returnFunc(ctx, screenName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.DisplayScreenName) *state.Session); ok {
		r0 = returnFunc(ctx, screenName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*state.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.DisplayScreenName) error); ok {
		r1 = returnFunc(ctx, screenName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockSessionRegistry_AddSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSession'
type mockSessionRegistry_AddSession_Call struct {
	*mock.Call
}

// AddSession is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.DisplayScreenName
func (_e *mockSessionRegistry_Expecter) AddSession(ctx interface{}, screenName interface{}) *mockSessionRegistry_AddSession_Call {
	return &mockSessionRegistry_AddSession_Call{Call: _e.mock.On("AddSession", ctx, screenName)}
}

func (_c *mockSessionRegistry_AddSession_Call) Run(run func(ctx context.Context, screenName state.DisplayScreenName)) *mockSessionRegistry_AddSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.DisplayScreenName
		if args[1] != nil {
			arg1 = args[1].(state.DisplayScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockSessionRegistry_AddSession_Call) Return(session *state.Session, err error) *mockSessionRegistry_AddSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *mockSessionRegistry_AddSession_Call) RunAndReturn(run func(ctx context.Context, screenName state.DisplayScreenName) (*state.Session, error)) *mockSessionRegistry_AddSession_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveSession provides a mock function for the type mockSessionRegistry
func (_mock *mockSessionRegistry) RemoveSession(sess *state.Session) {
	_mock.Called(sess)
	return
}

// mockSessionRegistry_RemoveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSession'
type mockSessionRegistry_RemoveSession_Call struct {
	*mock.Call
}

// RemoveSession is a helper method to define mock.On call
//   - sess *state.Session
func (_e *mockSessionRegistry_Expecter) RemoveSession(sess interface{}) *mockSessionRegistry_RemoveSession_Call {
	return &mockSessionRegistry_RemoveSession_Call{Call: _e.mock.On("RemoveSession", sess)}
}

func (_c *mockSessionRegistry_RemoveSession_Call) Run(run func(sess *state.Session)) *mockSessionRegistry_RemoveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *state.Session
		if args[0] != nil {
			arg0 = args[0].(*state.Session)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockSessionRegistry_RemoveSession_Call) Return() *mockSessionRegistry_RemoveSession_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockSessionRegistry_RemoveSession_Call) RunAndReturn(run func(sess *state.Session)) *mockSessionRegistry_RemoveSession_Call {
	_c.Run(run)
	return _c
}
