// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package foodgroup

import (
	"context"

	"github.com/mk6i/open-oscar-server/state"
	mock "github.com/stretchr/testify/mock"
)

// newMockChatSessionRegistry creates a new instance of mockChatSessionRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockChatSessionRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockChatSessionRegistry {
	mock := &mockChatSessionRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockChatSessionRegistry is an autogenerated mock type for the ChatSessionRegistry type
type mockChatSessionRegistry struct {
	mock.Mock
}

type mockChatSessionRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *mockChatSessionRegistry) EXPECT() *mockChatSessionRegistry_Expecter {
	return &mockChatSessionRegistry_Expecter{mock: &_m.Mock}
}

// AddSession provides a mock function for the type mockChatSessionRegistry
func (_mock *mockChatSessionRegistry) AddSession(ctx context.Context, chatCookie string, screenName state.DisplayScreenName, cfg ...func(sess *state.Session)) (*state.SessionInstance, error) {
	// func(sess *state.Session)
	_va := make([]interface{}, len(cfg))
	for _i := range cfg {
		_va[_i] = cfg[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, chatCookie, screenName)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddSession")
	}

	var r0 *state.SessionInstance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, state.DisplayScreenName, ...func(sess *state.Session)) (*state.SessionInstance, error)); ok {
		return returnFunc(ctx, chatCookie, screenName, cfg...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, state.DisplayScreenName, ...func(sess *state.Session)) *state.SessionInstance); ok {
		r0 = returnFunc(ctx, chatCookie, screenName, cfg...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*state.SessionInstance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, state.DisplayScreenName, ...func(sess *state.Session)) error); ok {
		r1 = returnFunc(ctx, chatCookie, screenName, cfg...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockChatSessionRegistry_AddSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSession'
type mockChatSessionRegistry_AddSession_Call struct {
	*mock.Call
}

// AddSession is a helper method to define mock.On call
//   - ctx context.Context
//   - chatCookie string
//   - screenName state.DisplayScreenName
//   - cfg ...func(sess *state.Session)
func (_e *mockChatSessionRegistry_Expecter) AddSession(ctx interface{}, chatCookie interface{}, screenName interface{}, cfg ...interface{}) *mockChatSessionRegistry_AddSession_Call {
	return &mockChatSessionRegistry_AddSession_Call{Call: _e.mock.On("AddSession",
		append([]interface{}{ctx, chatCookie, screenName}, cfg...)...)}
}

func (_c *mockChatSessionRegistry_AddSession_Call) Run(run func(ctx context.Context, chatCookie string, screenName state.DisplayScreenName, cfg ...func(sess *state.Session))) *mockChatSessionRegistry_AddSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 state.DisplayScreenName
		if args[2] != nil {
			arg2 = args[2].(state.DisplayScreenName)
		}
		var arg3 []func(sess *state.Session)
		variadicArgs := make([]func(sess *state.Session), len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(func(sess *state.Session))
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *mockChatSessionRegistry_AddSession_Call) Return(sessionInstance *state.SessionInstance, err error) *mockChatSessionRegistry_AddSession_Call {
	_c.Call.Return(sessionInstance, err)
	return _c
}

func (_c *mockChatSessionRegistry_AddSession_Call) RunAndReturn(run func(ctx context.Context, chatCookie string, screenName state.DisplayScreenName, cfg ...func(sess *state.Session)) (*state.SessionInstance, error)) *mockChatSessionRegistry_AddSession_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveSession provides a mock function for the type mockChatSessionRegistry
func (_mock *mockChatSessionRegistry) RemoveSession(sess *state.Session) {
	_mock.Called(sess)
	return
}

// mockChatSessionRegistry_RemoveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSession'
type mockChatSessionRegistry_RemoveSession_Call struct {
	*mock.Call
}

// RemoveSession is a helper method to define mock.On call
//   - sess *state.Session
func (_e *mockChatSessionRegistry_Expecter) RemoveSession(sess interface{}) *mockChatSessionRegistry_RemoveSession_Call {
	return &mockChatSessionRegistry_RemoveSession_Call{Call: _e.mock.On("RemoveSession", sess)}
}

func (_c *mockChatSessionRegistry_RemoveSession_Call) Run(run func(sess *state.Session)) *mockChatSessionRegistry_RemoveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *state.Session
		if args[0] != nil {
			arg0 = args[0].(*state.Session)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockChatSessionRegistry_RemoveSession_Call) Return() *mockChatSessionRegistry_RemoveSession_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockChatSessionRegistry_RemoveSession_Call) RunAndReturn(run func(sess *state.Session)) *mockChatSessionRegistry_RemoveSession_Call {
	_c.Run(run)
	return _c
}
