// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package foodgroup

import (
	"context"

	"github.com/mk6i/open-oscar-server/state"
	mock "github.com/stretchr/testify/mock"
)

// newMockBuddyAddedNotifierDeduper creates a new instance of mockBuddyAddedNotifierDeduper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBuddyAddedNotifierDeduper(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBuddyAddedNotifierDeduper {
	mock := &mockBuddyAddedNotifierDeduper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockBuddyAddedNotifierDeduper is an autogenerated mock type for the BuddyAddedNotifierDeduper type
type mockBuddyAddedNotifierDeduper struct {
	mock.Mock
}

type mockBuddyAddedNotifierDeduper_Expecter struct {
	mock *mock.Mock
}

func (_m *mockBuddyAddedNotifierDeduper) EXPECT() *mockBuddyAddedNotifierDeduper_Expecter {
	return &mockBuddyAddedNotifierDeduper_Expecter{mock: &_m.Mock}
}

// HasBuddyAddedNotification provides a mock function for the type mockBuddyAddedNotifierDeduper
func (_mock *mockBuddyAddedNotifierDeduper) HasBuddyAddedNotification(ctx context.Context, granter state.IdentScreenName, requester state.IdentScreenName) (bool, error) {
	ret := _mock.Called(ctx, granter, requester)

	if len(ret) == 0 {
		panic("no return value specified for HasBuddyAddedNotification")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, state.IdentScreenName) (bool, error)); ok {
		return returnFunc(ctx, granter, requester)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, state.IdentScreenName) bool); ok {
		r0 = returnFunc(ctx, granter, requester)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.IdentScreenName, state.IdentScreenName) error); ok {
		r1 = returnFunc(ctx, granter, requester)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockBuddyAddedNotifierDeduper_HasBuddyAddedNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasBuddyAddedNotification'
type mockBuddyAddedNotifierDeduper_HasBuddyAddedNotification_Call struct {
	*mock.Call
}

// HasBuddyAddedNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - granter state.IdentScreenName
//   - requester state.IdentScreenName
func (_e *mockBuddyAddedNotifierDeduper_Expecter) HasBuddyAddedNotification(ctx interface{}, granter interface{}, requester interface{}) *mockBuddyAddedNotifierDeduper_HasBuddyAddedNotification_Call {
	return &mockBuddyAddedNotifierDeduper_HasBuddyAddedNotification_Call{Call: _e.mock.On("HasBuddyAddedNotification", ctx, granter, requester)}
}

func (_c *mockBuddyAddedNotifierDeduper_HasBuddyAddedNotification_Call) Run(run func(ctx context.Context, granter state.IdentScreenName, requester state.IdentScreenName)) *mockBuddyAddedNotifierDeduper_HasBuddyAddedNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		var arg2 state.IdentScreenName
		if args[2] != nil {
			arg2 = args[2].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockBuddyAddedNotifierDeduper_HasBuddyAddedNotification_Call) Return(b bool, err error) *mockBuddyAddedNotifierDeduper_HasBuddyAddedNotification_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockBuddyAddedNotifierDeduper_HasBuddyAddedNotification_Call) RunAndReturn(run func(ctx context.Context, granter state.IdentScreenName, requester state.IdentScreenName) (bool, error)) *mockBuddyAddedNotifierDeduper_HasBuddyAddedNotification_Call {
	_c.Call.Return(run)
	return _c
}

// RecordBuddyAddedNotification provides a mock function for the type mockBuddyAddedNotifierDeduper
func (_mock *mockBuddyAddedNotifierDeduper) RecordBuddyAddedNotification(ctx context.Context, granter state.IdentScreenName, requester state.IdentScreenName) error {
	ret := _mock.Called(ctx, granter, requester)

	if len(ret) == 0 {
		panic("no return value specified for RecordBuddyAddedNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, state.IdentScreenName) error); ok {
		r0 = returnFunc(ctx, granter, requester)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockBuddyAddedNotifierDeduper_RecordBuddyAddedNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordBuddyAddedNotification'
type mockBuddyAddedNotifierDeduper_RecordBuddyAddedNotification_Call struct {
	*mock.Call
}

// RecordBuddyAddedNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - granter state.IdentScreenName
//   - requester state.IdentScreenName
func (_e *mockBuddyAddedNotifierDeduper_Expecter) RecordBuddyAddedNotification(ctx interface{}, granter interface{}, requester interface{}) *mockBuddyAddedNotifierDeduper_RecordBuddyAddedNotification_Call {
	return &mockBuddyAddedNotifierDeduper_RecordBuddyAddedNotification_Call{Call: _e.mock.On("RecordBuddyAddedNotification", ctx, granter, requester)}
}

func (_c *mockBuddyAddedNotifierDeduper_RecordBuddyAddedNotification_Call) Run(run func(ctx context.Context, granter state.IdentScreenName, requester state.IdentScreenName)) *mockBuddyAddedNotifierDeduper_RecordBuddyAddedNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		var arg2 state.IdentScreenName
		if args[2] != nil {
			arg2 = args[2].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockBuddyAddedNotifierDeduper_RecordBuddyAddedNotification_Call) Return(err error) *mockBuddyAddedNotifierDeduper_RecordBuddyAddedNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockBuddyAddedNotifierDeduper_RecordBuddyAddedNotification_Call) RunAndReturn(run func(ctx context.Context, granter state.IdentScreenName, requester state.IdentScreenName) error) *mockBuddyAddedNotifierDeduper_RecordBuddyAddedNotification_Call {
	_c.Call.Return(run)
	return _c
}
