// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/mk6i/open-oscar-server/state"
	mock "github.com/stretchr/testify/mock"
)

// newMockLinkedAccountManager creates a new instance of mockLinkedAccountManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockLinkedAccountManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockLinkedAccountManager {
	mock := &mockLinkedAccountManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockLinkedAccountManager is an autogenerated mock type for the LinkedAccountManager type
type mockLinkedAccountManager struct {
	mock.Mock
}

type mockLinkedAccountManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockLinkedAccountManager) EXPECT() *mockLinkedAccountManager_Expecter {
	return &mockLinkedAccountManager_Expecter{mock: &_m.Mock}
}

// DeleteAllLinkedAccounts provides a mock function for the type mockLinkedAccountManager
func (_mock *mockLinkedAccountManager) DeleteAllLinkedAccounts(ctx context.Context, screenName state.IdentScreenName) error {
	ret := _mock.Called(ctx, screenName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllLinkedAccounts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) error); ok {
		r0 = returnFunc(ctx, screenName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockLinkedAccountManager_DeleteAllLinkedAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllLinkedAccounts'
type mockLinkedAccountManager_DeleteAllLinkedAccounts_Call struct {
	*mock.Call
}

// DeleteAllLinkedAccounts is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
func (_e *mockLinkedAccountManager_Expecter) DeleteAllLinkedAccounts(ctx interface{}, screenName interface{}) *mockLinkedAccountManager_DeleteAllLinkedAccounts_Call {
	return &mockLinkedAccountManager_DeleteAllLinkedAccounts_Call{Call: _e.mock.On("DeleteAllLinkedAccounts", ctx, screenName)}
}

func (_c *mockLinkedAccountManager_DeleteAllLinkedAccounts_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName)) *mockLinkedAccountManager_DeleteAllLinkedAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockLinkedAccountManager_DeleteAllLinkedAccounts_Call) Return(err error) *mockLinkedAccountManager_DeleteAllLinkedAccounts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockLinkedAccountManager_DeleteAllLinkedAccounts_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName) error) *mockLinkedAccountManager_DeleteAllLinkedAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLinkedAccount provides a mock function for the type mockLinkedAccountManager
func (_mock *mockLinkedAccountManager) DeleteLinkedAccount(ctx context.Context, screenName state.IdentScreenName, linkedScreenName state.IdentScreenName) error {
	ret := _mock.Called(ctx, screenName, linkedScreenName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLinkedAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, state.IdentScreenName) error); ok {
		r0 = returnFunc(ctx, screenName, linkedScreenName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockLinkedAccountManager_DeleteLinkedAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLinkedAccount'
type mockLinkedAccountManager_DeleteLinkedAccount_Call struct {
	*mock.Call
}

// DeleteLinkedAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
//   - linkedScreenName state.IdentScreenName
func (_e *mockLinkedAccountManager_Expecter) DeleteLinkedAccount(ctx interface{}, screenName interface{}, linkedScreenName interface{}) *mockLinkedAccountManager_DeleteLinkedAccount_Call {
	return &mockLinkedAccountManager_DeleteLinkedAccount_Call{Call: _e.mock.On("DeleteLinkedAccount", ctx, screenName, linkedScreenName)}
}

func (_c *mockLinkedAccountManager_DeleteLinkedAccount_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName, linkedScreenName state.IdentScreenName)) *mockLinkedAccountManager_DeleteLinkedAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		var arg2 state.IdentScreenName
		if args[2] != nil {
			arg2 = args[2].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockLinkedAccountManager_DeleteLinkedAccount_Call) Return(err error) *mockLinkedAccountManager_DeleteLinkedAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockLinkedAccountManager_DeleteLinkedAccount_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName, linkedScreenName state.IdentScreenName) error) *mockLinkedAccountManager_DeleteLinkedAccount_Call {
	_c.Call.Return(run)
	return _c
}

// InsertLinkedAccount provides a mock function for the type mockLinkedAccountManager
func (_mock *mockLinkedAccountManager) InsertLinkedAccount(ctx context.Context, screenName state.IdentScreenName, linkedScreenName state.IdentScreenName) error {
	ret := _mock.Called(ctx, screenName, linkedScreenName)

	if len(ret) == 0 {
		panic("no return value specified for InsertLinkedAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, state.IdentScreenName) error); ok {
		r0 = returnFunc(ctx, screenName, linkedScreenName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockLinkedAccountManager_InsertLinkedAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertLinkedAccount'
type mockLinkedAccountManager_InsertLinkedAccount_Call struct {
	*mock.Call
}

// InsertLinkedAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
//   - linkedScreenName state.IdentScreenName
func (_e *mockLinkedAccountManager_Expecter) InsertLinkedAccount(ctx interface{}, screenName interface{}, linkedScreenName interface{}) *mockLinkedAccountManager_InsertLinkedAccount_Call {
	return &mockLinkedAccountManager_InsertLinkedAccount_Call{Call: _e.mock.On("InsertLinkedAccount", ctx, screenName, linkedScreenName)}
}

func (_c *mockLinkedAccountManager_InsertLinkedAccount_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName, linkedScreenName state.IdentScreenName)) *mockLinkedAccountManager_InsertLinkedAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		var arg2 state.IdentScreenName
		if args[2] != nil {
			arg2 = args[2].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockLinkedAccountManager_InsertLinkedAccount_Call) Return(err error) *mockLinkedAccountManager_InsertLinkedAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockLinkedAccountManager_InsertLinkedAccount_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName, linkedScreenName state.IdentScreenName) error) *mockLinkedAccountManager_InsertLinkedAccount_Call {
	_c.Call.Return(run)
	return _c
}

// LinkedAccounts provides a mock function for the type mockLinkedAccountManager
func (_mock *mockLinkedAccountManager) LinkedAccounts(ctx context.Context, screenName state.IdentScreenName) ([]state.IdentScreenName, error) {
	ret := _mock.Called(ctx, screenName)

	if len(ret) == 0 {
		panic("no return value specified for LinkedAccounts")
	}

	var r0 []state.IdentScreenName
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) ([]state.IdentScreenName, error)); ok {
		return returnFunc(ctx, screenName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) []state.IdentScreenName); ok {
		r0 = returnFunc(ctx, screenName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]state.IdentScreenName)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.IdentScreenName) error); ok {
		r1 = returnFunc(ctx, screenName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockLinkedAccountManager_LinkedAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkedAccounts'
type mockLinkedAccountManager_LinkedAccounts_Call struct {
	*mock.Call
}

// LinkedAccounts is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
func (_e *mockLinkedAccountManager_Expecter) LinkedAccounts(ctx interface{}, screenName interface{}) *mockLinkedAccountManager_LinkedAccounts_Call {
	return &mockLinkedAccountManager_LinkedAccounts_Call{Call: _e.mock.On("LinkedAccounts", ctx, screenName)}
}

func (_c *mockLinkedAccountManager_LinkedAccounts_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName)) *mockLinkedAccountManager_LinkedAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockLinkedAccountManager_LinkedAccounts_Call) Return(identScreenNames []state.IdentScreenName, err error) *mockLinkedAccountManager_LinkedAccounts_Call {
	_c.Call.Return(identScreenNames, err)
	return _c
}

func (_c *mockLinkedAccountManager_LinkedAccounts_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName) ([]state.IdentScreenName, error)) *mockLinkedAccountManager_LinkedAccounts_Call {
	_c.Call.Return(run)
	return _c
}
